name: Build Model proto

on:
  push:
    paths:
      - '/model-proto/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: build and publish to github packages
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          cd /model-proto
          mvn -B package --file pom.xml
          mvn -B deploy --file pom.xml