name: Build Model proto

on:
  push:
    branches:
      - main  # Chạy workflow này khi có sự thay đổi trên nhánh chính (main)
  pull_request:
    branches:
      - main  # Chạy workflow khi có pull request vào nhánh chính

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: build and publish to github packages
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          cd ./model-proto
          pwd
          mvn -B package --file pom.xml
          mvn -B deploy --file pom.xml